### ISSUE TITLE
ts2gs exports file to wrong folder

### ISSUE THREAD

**Issue by Whyser** [johnsoncodehk/ts2gamesparks#2]
Hey! First off, thanks a lot for this "lib"!

I think I've found a "simple" issue. If you only have one folder (example: ./modules/main.ts) and use "npm run start" the main.js will end up in the root of dist-folder (example: ./dist/main.ts). If I add another folder with a file in it (example: event/test.ts) this issue is solved (and both files will end up in correct folders). I'm not really a Javascript guy and I'm betting you can figure out this issue in a few minutes.

Thanks again!

**Comment by johnsoncodehk** [comment]
Thank you figure out the problem difficult to find.
This problem can be solved by writing ```"rootDir": "./"``` to tsconfig.json. I have updated the example tsconfig.json.
https://github.com/johnsoncodehk/gamesparks-cloud-code-typescript-example/commit/9014a7251704197bb83d049799e9c2433680231a

**Comment by Whyser** [comment]
Awesome, thank you! In my case it was "./src" that was needed.
