### ISSUE TITLE
Allow nested structure in modules folder

### ISSUE THREAD

**Issue by mixecan** [johnsoncodehk/ts2gamesparks#4]
First off, thanks for this library!

Is it possible to have a nested structure in the modules folder? This would allow external projects to be integrated using submodules/subtrees.

**Comment by johnsoncodehk** [comment]
Thank you for your proposal.
I have a preliminary idea to implement this feature and I will verify its feasibility.

**Comment by johnsoncodehk** [comment]
I implemented it in the develop branch, I have passed the self-test, I am worried that there are problems I have not considered, can you try it? thank you.
Commit: https://github.com/johnsoncodehk/ts2gamesparks/commit/21f5445f346b80f9b3101407a588fad4d2079c3f

**Comment by mixecan** [comment]
Looks good to me, but I can't be completely sure until I start merging different projects in my live env.

It may need some weeks

**Comment by mixecan** [comment]
I get a bug when multiple elements are imported from the same nested module.

If I have `import { funcA, funcB, funcC } from "nested/moduleA"` I get the following require
```js
require('nested__moduleAAA');
```

The problem is that:
- the module is renamed and gets longer (`/` is replaced with `__`)
- the import statement is updated with the new name once for each imported element
- for each update the replace location refers to the original string that's shorter than renamed module

In my example this happens
1. funcA: `require('nested/moduleA')` => `require('nested__moduleA')`
2. funcB: `require('nested__moduleA')` => `require('nested__moduleAA')`
3. funcC: `require('nested__moduleAA')` => `require('nested__moduleAAA')`

**Comment by johnsoncodehk** [comment]
Thank you for accurately targeting this bug!
I have fixed it in this commit: https://github.com/johnsoncodehk/ts2gamesparks/commit/fc5f08ebadd29dc3574b002ae63e599feb701441
