### ISSUE TITLE
method names written as "exports.methodName" instead of...

### ISSUE THREAD

**Issue by Whyser** [johnsoncodehk/ts2gamesparks#7]
Hey, I was gonna let a friend start using this and he's uses the latest commit from this repo, it seems that the following is happening for him:
**BlaBla.ts**
```
export function testFunc()
{
//..
}
```
becomes...
**BlaBla.js:**
```
function testFunc()
{
//..
}
exports.testFunc = testFunc;
```

While my becomes:
```
function module_BlaBla_testFunc()
{
//..
}
var module_BlaBla = {
    testFunc : module_BlaBla_testFunc 
};
```

I'm not sure what version I'm using (or if I made some modifications to it) as I've not updated for quite a while, but when I sent him my ts2gamesparks-folder it became same as mine. His version is obviously cleaner, but it causes GameSpark to whine about `exports` is not defined.

**Comment by johnsoncodehk** [comment]
Your version is correct, please make sure your friend's tsconfig.json baseUrl property points to the modules folder, because ts2gs will only compile the baseUrl directory into the Cloud Code module.

**Comment by johnsoncodehk** [comment]
I have updated the readme, if there is still a problem, please install the latest version of ts2gamesparks, then follow the readme instructions.

**Comment by Whyser** [comment]
Thanks for the quick response, I will tell him to try this out.

**Comment by Whyser** [comment]
Sorry to open this again. 

The problem seems to be that you only "convert" files that are inside the baseUrl (which is ./src/modules) and if baseUrl is not "./src/modules" it can't resolve some imports. I convert the whole ./src/ folder since GameSparks has multiple folders other than "modules" (example: message-user, message-global etc).

In my version, you don't seem to use baseUrl to select which files to convert, which is the reason why my version was working. The only way (in the latest version) to convert the whole ./src/ folder is to change the baseUrl, but changing it will cause imports to not be correct.

**Comment by johnsoncodehk** [comment]
baseUrl is a file for converting the module format. For other files that are not modules, it will be converted according to the format of the non-module.

Would you mind emailing me the wrong part of your project and let me check the problem?

**Comment by Whyser** [comment]
I've sent an email

**Comment by johnsoncodehk** [comment]
I may have found the cause of the problem. It is probably because your message-global and message-user use the export keyword. Is export necessary for these scripts?

**Comment by johnsoncodehk** [comment]
In principle, in addition to the files in the modules and rtModules folder, you should not use export anywhere.

**Comment by Whyser** [comment]
All my .ts files use the export (as you can see). I understand the logic that export may only make sense in modules since that's where "libs" are (methods which may be used somewhere else). But it seems like it should be a non-issue to allow export anywhere?

**Comment by johnsoncodehk** [comment]
Yes, for general ts projects, export should not be a problem anywhere. But for the GameSparks project, export will cause typescript to generate exports.xxx= xxx statements, and exports are undefined in GameSparks, so ts2gamesparks converts these The statement makes it meaningful.

But these conversions are not without cost, because the conversion will rename some elements, if these elements are not strongly typed, for example: this\["myFunc"\](), an undefined error will occur.

In the old version of ts2gamesparks, since all the exports were renamed, there is no current problem.

Can you remove the export other than modules to solve the problem?
Also, do you think the old version of the method is better?

**Comment by johnsoncodehk** [comment]
For directories other than modules and rtMoudles, export doesn't really work, because based on the limitations of GameSparks, you can't introduce it elsewhere.

**Comment by Whyser** [comment]
It seems to work when export is removed. With regards to the "best method", I can't really say. I don't mind the methods getting weird names, since normally I don't look into the .js files unless there's some issue.

**Comment by johnsoncodehk** [comment]
I will see if I improve it (such as automatically deleting export or throwing an error), thank you for letting me know about this situation :)

**Comment by Whyser** [comment]
Thank you, for helping!

**Comment by Whyser** [comment]
Hey, sorry to open up this again. But I realized that removing "export" from methods not inside the module folder will cause conflict when methods are named the same. So now..in hindsight it would actually be good if use of "export" was allowed.

**Comment by johnsoncodehk** [comment]
I also thought of similar questions, but I got the opposite conclusion.

one example:
- event/apple.ts
- modules/apple.ts

If both scripts exist and export function eat(), eat() will be renamed to module_apple_eat() at the same time, which will result in a naming conflict.

Maybe I didn't understand the case you said. Can you give an example?

**Comment by Whyser** [comment]
If I have the following:

event/apple.ts
event/pear.ts

And both have a method named:
```
function peel()
{
}
```
It will cause a conflict saying peel method already exists. Using `export` will eliminate issue, but will in turn cause the previous issue.

**Comment by johnsoncodehk** [comment]
I just confirmed this problem, this is a quick fix:

Create modules/empty.ts, then import "empty" in event/apple.ts and event/pear.ts

I will see if there is a better way to solve it, you can keep the issue.

**Comment by Whyser** [comment]
Thanks for the quick response and "fix".

**Comment by johnsoncodehk** [comment]
Hi @Whyser , I haven't found a direct fix yet, but there is a better quick fix:

Add ```export interface FixScope { }``` to apple.ts and pear.ts.

This does not require the creation of additional file and does not generate additional js code.

**Comment by johnsoncodehk** [comment]
I finally found this issue: https://github.com/Microsoft/TypeScript/issues/18232

Typescript can't handle this problem, but they use ```export { }``` to solve it, which is much better than what I suggested.

**Comment by johnsoncodehk** [comment]
Closed because already has a solution
