### ISSUE TITLE
It is possible to change require to requireOnce for Real-time Script?

### ISSUE THREAD

**Issue by frize** [johnsoncodehk/ts2gamesparks#8]
I am facing a problem when the source code in realtime becomes bigger, the server took more than 10 seconds to load the source code only, which is insane.

I think requireOnce could improve the loading speed in the Realtime server.
Currently, the tool only uses requireOnce for event and module, it does not apply for Realtime scripts.

**Comment by johnsoncodehk** [comment]
As I know rtScript is based on commond js, require is equivalent to requireOnce of event. I guess requireOnce is undefined in rtScript.
I have not used gamesparks now. You can try to replace require in the output js of rtScript with requireOnce. If the problem can be solved, I would be happy to change require to requireOnce.
